name: Waka Readme

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: false                    # ← IMPORTANT: Turn off default title
          BLOCKS: ░▒▓                          # ← IMPORTANT: Custom blocks
          TIME_RANGE: LAST_7_DAYS
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          SHOW_TOTAL: true
